module.exports = {
  '@db/(.*)': '<rootDir>/src/db/$1',
  '@data-access/(.*)': '<rootDir>/src/data-access/$1',
  '@models': '<rootDir>/src/models/index',
  '@constants': '<rootDir>/src/constants/index',
  '@models/(.*)': '<rootDir>/src/models/$1',
  '@tools/(.*)': '<rootDir>/src/tools/$1',
  '@graphql/(.*)': '<rootDir>/src/graphql/$1',
  '@utils/(.*)': '<rootDir>/src/utils/$1',
  '@services/(.*)': '<rootDir>/src/services/$1',
  '@controllers/(.*)': '<rootDir>/src/controllers/$1',
  '@services': '<rootDir>/src/services/index',
  '@sockets': '<rootDir>/src/sockets/index',
  '@data-access': '<rootDir>/src/data-access/index',
  '@permissions/(.*)': '<rootDir>/src/permissions/$1',
  '@controllers': '<rootDir>/src/controllers/index',
  '@scripts/(.*)': '<rootDir>/src/scripts/$1',
  '@test/(.*)': '<rootDir>/src/jest/$1',
  '@db-fixtures': '<rootDir>/db/src/fixtures/index',
  '@db-types': '<rootDir>/db/src/types/index',
  '@db-tables': '<rootDir>/db/src/tables/index',
  //   '^generated/(.*)': '<rootDir>/src/generated/$1',
  //   '^services/(.*)': '<rootDir>/src/services/$1',
  //   '^models/(.*)': '<rootDir>/src/models/$1',
};
