const eventPaymentIntentSucceeded = {
  id: 'evt_3K1Q0jIElsOvFh8G1KxSfkgJ',
  object: 'event',
  api_version: '2020-03-02',
  created: 1638254418,
  data: {
    object: {
      id: 'ch_3K1Q0jIElsOvFh8G1qwlFRCX',
      object: 'charge',
      amount: 2000,
      amount_captured: 2000,
      amount_refunded: 0,
      application: null,
      application_fee: null,
      application_fee_amount: null,
      balance_transaction: 'txn_3K1Q0jIElsOvFh8G1U3Pohb4',
      billing_details: [Object],
      calculated_statement_descriptor: 'GOKUDOS SDN BHD',
      captured: true,
      created: 1638254417,
      currency: 'usd',
      customer: null,
      description: '(created by Stripe CLI)',
      destination: null,
      dispute: null,
      disputed: false,
      failure_code: null,
      failure_message: null,
      fraud_details: {},
      invoice: null,
      livemode: false,
      metadata: {},
      on_behalf_of: null,
      order: null,
      outcome: [Object],
      paid: true,
      payment_intent: 'pi_3K1Q0jIElsOvFh8G1GGoStcX',
      payment_method: 'pm_1K1Q0jIElsOvFh8GuZN7cx9a',
      payment_method_details: [Object],
      receipt_email: null,
      receipt_number: null,
      receipt_url:
        'https://pay.stripe.com/receipts/acct_1GurDTIElsOvFh8G/ch_3K1Q0jIElsOvFh8G1qwlFRCX/rcpt_KgnbovaQgBQ1txsEhIVYSYoIOFIgXcs',
      refunded: false,
      refunds: [Object],
      review: null,
      shipping: [Object],
      source: null,
      source_transfer: null,
      statement_descriptor: null,
      statement_descriptor_suffix: null,
      status: 'succeeded',
      transfer_data: null,
      transfer_group: null,
    },
  },
  livemode: false,
  pending_webhooks: 2,
  request: {
    id: 'req_4dvA8TxZ4hBGbg',
    idempotency_key: '16580fd8-c961-4371-b70a-499f1c845047',
  },
  type: 'charge.succeeded',
};

const eventInvoicePaymentSucceeded = {
  id: 'evt_1K1WEPIElsOvFh8Ga7rbRc7L',
  object: 'event',
  api_version: '2020-03-02',
  created: 1638278328,
  data: {
    object: {
      id: 'in_1K1WEMIElsOvFh8GT8Nnpt62',
      object: 'invoice',
      account_country: 'MY',
      account_name: 'GoKudos Sdn Bhd',
      account_tax_ids: null,
      amount_due: 2000,
      amount_paid: 2000,
      amount_remaining: 0,
      application_fee_amount: null,
      attempt_count: 1,
      attempted: true,
      auto_advance: false,
      automatic_tax: {
        enabled: false,
        status: null,
      },
      billing_reason: 'manual',
      charge: 'ch_3K1WENIElsOvFh8G1P3d5eLA',
      collection_method: 'charge_automatically',
      created: 1638278326,
      currency: 'usd',
      custom_fields: null,
      customer: 'cus_Kgu2zQVmgQcBud',
      customer_address: null,
      customer_email: null,
      customer_name: null,
      customer_phone: null,
      customer_shipping: null,
      customer_tax_exempt: 'none',
      customer_tax_ids: [],
      default_payment_method: null,
      default_source: null,
      default_tax_rates: [],
      description: '(created by Stripe CLI)',
      discount: null,
      discounts: [],
      due_date: null,
      ending_balance: 0,
      footer: null,
      hosted_invoice_url:
        'https://invoice.stripe.com/i/acct_1GurDTIElsOvFh8G/test_YWNjdF8xR3VyRFRJRWxzT3ZGaDhHLF9LZ3UyRmtIWDV5aGZhaUZiYkE3UHd4bGNqSzFXOGRw0100LGvY4K6A',
      invoice_pdf:
        'https://pay.stripe.com/invoice/acct_1GurDTIElsOvFh8G/test_YWNjdF8xR3VyRFRJRWxzT3ZGaDhHLF9LZ3UyRmtIWDV5aGZhaUZiYkE3UHd4bGNqSzFXOGRw0100LGvY4K6A/pdf',
      last_finalization_error: null,
      lines: {
        object: 'list',
        data: [
          {
            id: 'il_1K1WELIElsOvFh8GP9ZNj25J',
            object: 'line_item',
            amount: 2000,
            currency: 'usd',
            description: '(created by Stripe CLI)',
            discount_amounts: [],
            discountable: true,
            discounts: [],
            invoice_item: 'ii_1K1WELIElsOvFh8GPZEOJZRu',
            livemode: false,
            metadata: {},
            period: {
              end: 1638278325,
              start: 1638278325,
            },
            plan: null,
            price: {
              id: 'price_1K1WELIElsOvFh8Geb82bEP6',
              object: 'price',
              active: false,
              billing_scheme: 'per_unit',
              created: 1638278325,
              currency: 'usd',
              livemode: false,
              lookup_key: null,
              metadata: {},
              nickname: null,
              product: 'prod_Kgu2TCtYwSoe6U',
              recurring: null,
              tax_behavior: 'unspecified',
              tiers_mode: null,
              transform_quantity: null,
              type: 'one_time',
              unit_amount: 2000,
              unit_amount_decimal: '2000',
            },
            proration: false,
            quantity: 1,
            subscription: null,
            tax_amounts: [],
            tax_rates: [],
            type: 'invoiceitem',
          },
        ],
        has_more: false,
        total_count: 1,
        url: '/v1/invoices/in_1K1WEMIElsOvFh8GT8Nnpt62/lines',
      },
      livemode: false,
      metadata: {},
      next_payment_attempt: null,
      number: 'A50351AC-0001',
      on_behalf_of: null,
      paid: true,
      payment_intent: 'pi_3K1WENIElsOvFh8G1hMRU8Kp',
      payment_settings: {
        payment_method_options: null,
        payment_method_types: null,
      },
      period_end: 1638278326,
      period_start: 1638278326,
      post_payment_credit_notes_amount: 0,
      pre_payment_credit_notes_amount: 0,
      quote: null,
      receipt_number: null,
      starting_balance: 0,
      statement_descriptor: null,
      status: 'paid',
      status_transitions: {
        finalized_at: 1638278327,
        marked_uncollectible_at: null,
        paid_at: 1638278327,
        voided_at: null,
      },
      subscription: null,
      subtotal: 2000,
      tax: null,
      tax_percent: null,
      test_clock: null,
      total: 2000,
      total_discount_amounts: [],
      total_tax_amounts: [],
      transfer_data: null,
      webhooks_delivered_at: null,
    },
  },
  livemode: false,
  pending_webhooks: 3,
  request: {
    id: 'req_X4f1VRmCeoe8H6',
    idempotency_key: '57c1848e-66cd-445b-96cc-9bce5c5b4d2d',
  },
  type: 'invoice.payment_succeeded',
};

const subscriptionCreatedResult = {
  id: 'sub_1K2TBxIElsOvFh8G64UvIT05',
  object: 'subscription',
  application_fee_percent: null,
  automatic_tax: { enabled: false },
  billing_cycle_anchor: 1638504973,
  billing_thresholds: null,
  cancel_at: null,
  cancel_at_period_end: false,
  canceled_at: null,
  collection_method: 'charge_automatically',
  created: 1638504973,
  current_period_end: 1641183373,
  current_period_start: 1638504973,
  customer: 'cus_Khsxv2DsLxU9Kx',
  days_until_due: null,
  default_payment_method: 'pm_1K2TBJIElsOvFh8GC4rVvgah',
  default_source: null,
  default_tax_rates: [],
  discount: null,
  ended_at: null,
  items: {
    object: 'list',
    data: [[Object]],
    has_more: false,
    total_count: 1,
    url: '/v1/subscription_items?subscription=sub_1K2TBxIElsOvFh8G64UvIT05',
  },
  latest_invoice: {
    id: 'in_1K2TBxIElsOvFh8GYftCAUPj',
    object: 'invoice',
    account_country: 'MY',
    account_name: 'GoKudos Sdn Bhd',
    account_tax_ids: null,
    amount_due: 36900,
    amount_paid: 0,
    amount_remaining: 36900,
    application_fee_amount: null,
    attempt_count: 0,
    attempted: true,
    auto_advance: true,
    automatic_tax: { enabled: false, status: null },
    billing_reason: 'subscription_create',
    charge: null,
    collection_method: 'charge_automatically',
    created: 1638504973,
    currency: 'myr',
    custom_fields: null,
    customer: 'cus_Khsxv2DsLxU9Kx',
    customer_address: null,
    customer_email: 'enoch@6biz.ai',
    customer_name: 'Enoch',
    customer_phone: null,
    customer_shipping: null,
    customer_tax_exempt: 'none',
    customer_tax_ids: [],
    default_payment_method: null,
    default_source: null,
    default_tax_rates: [],
    description: null,
    discount: null,
    discounts: [],
    due_date: null,
    ending_balance: 0,
    footer: null,
    hosted_invoice_url:
      'https://invoice.stripe.com/i/acct_1GurDTIElsOvFh8G/test_YWNjdF8xR3VyRFRJRWxzT3ZGaDhHLF9LaHN4WFlIM2lTZlRuclhuTUdlUndYZmI5OWw5NVRQ0100ShJfQlMp',
    invoice_pdf:
      'https://pay.stripe.com/invoice/acct_1GurDTIElsOvFh8G/test_YWNjdF8xR3VyRFRJRWxzT3ZGaDhHLF9LaHN4WFlIM2lTZlRuclhuTUdlUndYZmI5OWw5NVRQ0100ShJfQlMp/pdf',
    last_finalization_error: null,
    lines: {
      object: 'list',
      data: [Array],
      has_more: false,
      total_count: 1,
      url: '/v1/invoices/in_1K2TBxIElsOvFh8GYftCAUPj/lines',
    },
    livemode: false,
    metadata: {},
    next_payment_attempt: null,
    number: '32B4C0B6-0001',
    on_behalf_of: null,
    paid: false,
    payment_intent: {
      id: 'pi_3K2TByIElsOvFh8G09tSTtU5',
      object: 'payment_intent',
      amount: 36900,
      amount_capturable: 0,
      amount_received: 0,
      application: null,
      application_fee_amount: null,
      automatic_payment_methods: null,
      canceled_at: null,
      cancellation_reason: null,
      capture_method: 'automatic',
      charges: [Object],
      client_secret:
        'pi_3K2TByIElsOvFh8G09tSTtU5_secret_LgNAStFBfvt7GlH0RJdz9jBvH',
      confirmation_method: 'automatic',
      created: 1638504974,
      currency: 'myr',
      customer: 'cus_Khsxv2DsLxU9Kx',
      description: 'Subscription creation',
      invoice: 'in_1K2TBxIElsOvFh8GYftCAUPj',
      last_payment_error: null,
      livemode: false,
      metadata: {},
      next_action: [Object],
      on_behalf_of: null,
      payment_method: 'pm_1K2TBJIElsOvFh8GC4rVvgah',
      payment_method_options: [Object],
      payment_method_types: [Array],
      receipt_email: null,
      review: null,
      setup_future_usage: 'off_session',
      shipping: null,
      source: null,
      statement_descriptor: null,
      statement_descriptor_suffix: null,
      status: 'requires_action',
      transfer_data: null,
      transfer_group: null,
    },
    payment_settings: {
      payment_method_options: null,
      payment_method_types: null,
    },
    period_end: 1638504973,
    period_start: 1638504973,
    post_payment_credit_notes_amount: 0,
    pre_payment_credit_notes_amount: 0,
    quote: null,
    receipt_number: null,
    starting_balance: 0,
    statement_descriptor: null,
    status: 'open',
    status_transitions: {
      finalized_at: 1638504973,
      marked_uncollectible_at: null,
      paid_at: null,
      voided_at: null,
    },
    subscription: 'sub_1K2TBxIElsOvFh8G64UvIT05',
    subtotal: 36900,
    tax: null,
    test_clock: null,
    total: 36900,
    total_discount_amounts: [],
    total_tax_amounts: [],
    transfer_data: null,
    webhooks_delivered_at: null,
  },
  livemode: false,
  metadata: {},
  next_pending_invoice_item_invoice: null,
  pause_collection: null,
  payment_settings: {
    payment_method_options: null,
    payment_method_types: null,
  },
  pending_invoice_item_interval: null,
  pending_setup_intent: null,
  pending_update: null,
  plan: {
    id: 'price_1JFCMKIElsOvFh8GTotD9fY7',
    object: 'plan',
    active: true,
    aggregate_usage: null,
    amount: 36900,
    amount_decimal: '36900',
    billing_scheme: 'per_unit',
    created: 1626762196,
    currency: 'myr',
    interval: 'month',
    interval_count: 1,
    livemode: false,
    metadata: {},
    nickname: null,
    product: 'prod_JsyIeH2XeaBOFv',
    tiers_mode: null,
    transform_usage: null,
    trial_period_days: null,
    usage_type: 'licensed',
  },
  quantity: 1,
  schedule: null,
  start_date: 1638504973,
  status: 'incomplete',
  test_clock: null,
  transfer_data: null,
  trial_end: null,
  trial_start: null,
};

const subscriptionInsertResult = {
  id: 104,
  company_id: 1,
  package_id: 5,
  subscription_id: null,
  product_id: 'prod_HUBUYINmBWEyM6',
  price_id: 'price_1JFCMKIElsOvFh8GTotD9fY7',
  package_title: 'Premium',
  package_description: '',
  sms_quota: 300,
  phone_call_quota: 0,
  email_quota: 1200,
  whatsApp_quota: 500,
  price: '369.00',
  interval: 'month',
  interval_count: 1,
  start_date: '2021-12-02T20:16:15.000Z',
  end_date: '2022-01-02T20:16:14.000Z',
  cancel_date: null,
  status: 1,
  active: 1,
  created_by: 1,
  updated_by: 1,
  deleted_by: null,
  created_at: '2021-12-02T20:16:15.000Z',
  updated_at: '2021-12-02T20:16:15.000Z',
  deleted_at: null,

  id_text: 'c1d3050b-53ef-11ec-b4cc-06d04d56a954',
  data: {
    id: 5,
    slug: 'premium',
    title: 'Premium',
    active: 1,
    id_bin: { data: [Array], type: 'Buffer' },
    id_text: 'e3cf02ca-d556-11eb-ad52-0a529fa336f4',
    published: 1,
    sms_quota: 300,
    created_at: '2020-06-17T18:05:07.000Z',
    created_by: 4,
    deleted_at: null,
    deleted_by: 0,
    product_id: 'prod_HUBUYINmBWEyM6',
    updated_at: '2021-05-27T02:33:36.000Z',
    updated_by: 1,
    description: '',
    email_quota: 1200,
    whatsapp_quota: 500,
    phone_call_quota: 0,
  },
};

export default {
  eventPaymentIntentSucceeded,
  eventInvoicePaymentSucceeded,
  subscriptionCreatedResult,
  subscriptionInsertResult,
};
