import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  //await knex("table_name").del();

  // Inserts seed entries
  await knex('packages').insert([
    {
      product_id: 'prod_L0IyGPNg9hrUgu',
      title: 'Omni Starter',
      type: 1,
      created_at: knex.fn.now(),
      sms_quota: 0,
      phone_call_quota: 0,
      email_quota: 0,
      whatsapp_quota: 0,
      published: 1,
      active: 1,
      created_by: 1,
      slug: 'omni_starter',
      storage: 50,
    },
    {
      product_id: 'prod_L0J1W7yWmBE5Ys',
      title: 'Omni Pro',
      type: 1,
      created_at: knex.fn.now(),
      sms_quota: 0,
      phone_call_quota: 0,
      email_quota: 0,
      whatsapp_quota: 0,
      published: 1,
      active: 1,
      created_by: 1,
      slug: 'omni_pro',
      storage: 70,
    },
    {
      product_id: 'prod_L0J2jzoJeqCtMd',
      title: 'Omni Premium',
      type: 1,
      created_at: knex.fn.now(),
      sms_quota: 0,
      phone_call_quota: 0,
      email_quota: 0,
      whatsapp_quota: 0,
      published: 1,
      active: 1,
      created_by: 1,
      slug: 'omni_premium',
      storage: 100,
    },
    {
      product_id: 'prod_L0J71gY2hqttEI',
      title: 'Omni Time Attendance',
      type: 2,
      created_at: knex.fn.now(),
      sms_quota: 0,
      phone_call_quota: 0,
      email_quota: 0,
      whatsapp_quota: 0,
      published: 1,
      active: 1,
      created_by: 1,
      slug: 'time_attendance',
    },
    {
      product_id: 'prod_L0J9AEGwWR8UOa',
      title: 'Omni Project Management Tool',
      type: 3,
      created_at: knex.fn.now(),
      sms_quota: 0,
      phone_call_quota: 0,
      email_quota: 0,
      whatsapp_quota: 0,
      published: 1,
      active: 1,
      created_by: 1,
      slug: 'project_management_tool',
    },
    {
      product_id: 'prod_L1MNXLQKmCVdbR',
      title: 'Omni Plan 500',
      type: 4,
      created_at: knex.fn.now(),
      sms_quota: 0,
      phone_call_quota: 0,
      email_quota: 500,
      whatsapp_quota: 500,
      published: 1,
      active: 1,
      created_by: 1,
      slug: 'plan_500',
    },
    {
      product_id: 'prod_L1MOAfvzVB5SKA',
      title: 'Omni Plan 1000',
      type: 4,
      created_at: knex.fn.now(),
      sms_quota: 0,
      phone_call_quota: 0,
      email_quota: 1000,
      whatsapp_quota: 1000,
      published: 1,
      active: 1,
      created_by: 1,
      slug: 'plan_1000',
    },
    {
      product_id: 'prod_L1MPbubNDobWpj',
      title: 'Omni Plan 2000',
      type: 4,
      created_at: knex.fn.now(),
      sms_quota: 0,
      phone_call_quota: 0,
      email_quota: 2000,
      whatsapp_quota: 2000,
      published: 1,
      active: 1,
      created_by: 1,
      slug: 'plan_2000',
    },
    {
      product_id: 'prod_L27Fo4E1wwrtJx',
      title: 'Starter Bundle',
      type: 1,
      created_at: knex.fn.now(),
      sms_quota: 0,
      phone_call_quota: 0,
      email_quota: 0,
      whatsapp_quota: 0,
      published: 1,
      active: 1,
      created_by: 1,
      slug: 'starter_bundle',
      storage: 50,
    },
    {
      product_id: 'prod_L27Ghd3dAVNdQr',
      title: 'Pro Bundle',
      type: 1,
      created_at: knex.fn.now(),
      sms_quota: 0,
      phone_call_quota: 0,
      email_quota: 0,
      whatsapp_quota: 0,
      published: 1,
      active: 1,
      created_by: 1,
      slug: 'pro_bundle',
      storage: 70,
    },
    {
      product_id: 'prod_L27Gimw24hOiMo',
      title: 'Premium Bundle',
      type: 1,
      created_at: knex.fn.now(),
      sms_quota: 0,
      phone_call_quota: 0,
      email_quota: 0,
      whatsapp_quota: 0,
      published: 1,
      active: 1,
      created_by: 1,
      slug: 'premium_bundle',
      storage: 100,
    },
    {
      product_id: 'prod_L279NHzSckTgWw',
      title: 'Time Attendance Bundle',
      type: 2,
      created_at: knex.fn.now(),
      sms_quota: 0,
      phone_call_quota: 0,
      email_quota: 0,
      whatsapp_quota: 0,
      published: 1,
      active: 1,
      created_by: 1,
      slug: 'time_attendance_bundle',
      storage: 0,
    },
    {
      product_id: 'prod_L27A6ca6qifq2F',
      title: 'Project Management Tool Bundle',
      type: 3,
      created_at: knex.fn.now(),
      sms_quota: 0,
      phone_call_quota: 0,
      email_quota: 0,
      whatsapp_quota: 0,
      published: 1,
      active: 1,
      created_by: 1,
      slug: 'project_management_bundle',
      storage: 0,
    },
    {
      product_id: 'prod_L2VAtXCK08zcvl',
      title: 'Starter All Bundle',
      type: 1,
      created_at: knex.fn.now(),
      sms_quota: 0,
      phone_call_quota: 0,
      email_quota: 0,
      whatsapp_quota: 0,
      published: 1,
      active: 1,
      created_by: 1,
      slug: 'starter_all_bundle',
      storage: 50,
    },
    {
      product_id: 'prod_L2VCYi3QgKI7SL',
      title: 'Pro All Bundle',
      type: 1,
      created_at: knex.fn.now(),
      sms_quota: 0,
      phone_call_quota: 0,
      email_quota: 0,
      whatsapp_quota: 0,
      published: 1,
      active: 1,
      created_by: 1,
      slug: 'pro_all_bundle',
      storage: 70,
    },
    {
      product_id: 'prod_L2VCAXlWbS42tx',
      title: 'Premium All Bundle',
      type: 1,
      created_at: knex.fn.now(),
      sms_quota: 0,
      phone_call_quota: 0,
      email_quota: 0,
      whatsapp_quota: 0,
      published: 1,
      active: 1,
      created_by: 1,
      slug: 'premium_all_bundle',
      storage: 100,
    },
    {
      product_id: 'prod_L2VEwM3rhHSPGW',
      title: 'Time Attendance All Bundle',
      type: 2,
      created_at: knex.fn.now(),
      sms_quota: 0,
      phone_call_quota: 0,
      email_quota: 0,
      whatsapp_quota: 0,
      published: 1,
      active: 1,
      created_by: 1,
      slug: 'time_attendance_all_bundle',
    },
    {
      product_id: 'prod_L2VF9ujIMDCFRP',
      title: 'Project Management All Bundle',
      type: 3,
      created_at: knex.fn.now(),
      sms_quota: 0,
      phone_call_quota: 0,
      email_quota: 0,
      whatsapp_quota: 0,
      published: 1,
      active: 1,
      created_by: 1,
      slug: 'project_management_tool',
    },
    {
      product_id: 'prod_L2VH97kpKFcmKV',
      title: 'Plan 500 All Bundle',
      type: 4,
      created_at: knex.fn.now(),
      sms_quota: 0,
      phone_call_quota: 0,
      email_quota: 500,
      whatsapp_quota: 500,
      published: 1,
      active: 1,
      created_by: 1,
      slug: 'plan_500_all_bundle',
    },
    {
      product_id: 'prod_L2VI51VS1ozkx2',
      title: 'Plan 1000 All Bundle',
      type: 4,
      created_at: knex.fn.now(),
      sms_quota: 0,
      phone_call_quota: 0,
      email_quota: 1000,
      whatsapp_quota: 1000,
      published: 1,
      active: 1,
      created_by: 1,
      slug: 'plan_1000_all_bundle',
    },
    {
      product_id: 'prod_L2VOn5QjcHywiZ',
      title: 'Plan 2000 All Bundle',
      type: 4,
      created_at: knex.fn.now(),
      sms_quota: 0,
      phone_call_quota: 0,
      email_quota: 2000,
      whatsapp_quota: 2000,
      published: 1,
      active: 1,
      created_by: 1,
      slug: 'plan_2000_all_bundle',
    },
  ]);
}
