import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  //await knex("table_name").del();

  // Inserts seed entries
  await knex('packages').insert([
    {
      product_id: 'prod_L2VAtXCK08zcvl',
      title: 'Starter All Bundle',
      created_at: knex.fn.now(),
      sms_quota: 0,
      phone_call_quota: 0,
      email_quota: 0,
      whatsapp_quota: 0,
      published: 1,
      active: 1,
      created_by: 1,
      slug: 'starter_all_bundle',
      storage: 50,
    },
    {
      product_id: 'prod_L2VCYi3QgKI7SL',
      title: 'Pro All Bundle',
      created_at: knex.fn.now(),
      sms_quota: 0,
      phone_call_quota: 0,
      email_quota: 0,
      whatsapp_quota: 0,
      published: 1,
      active: 1,
      created_by: 1,
      slug: 'pro_all_bundle',
      storage: 70,
    },
    {
      product_id: 'prod_L2VCAXlWbS42tx',
      title: 'Premium All Bundle',
      created_at: knex.fn.now(),
      sms_quota: 0,
      phone_call_quota: 0,
      email_quota: 0,
      whatsapp_quota: 0,
      published: 1,
      active: 1,
      created_by: 1,
      slug: 'premium_all_bundle',
      storage: 100,
    },
    {
      product_id: 'prod_L2VEwM3rhHSPGW',
      title: 'Time Attendance All Bundle',
      created_at: knex.fn.now(),
      sms_quota: 0,
      phone_call_quota: 0,
      email_quota: 0,
      whatsapp_quota: 0,
      published: 1,
      active: 1,
      created_by: 1,
      slug: 'time_attendance_all_bundle',
    },
    {
      product_id: 'prod_L2VF9ujIMDCFRP',
      title: 'Project Management All Bundle',
      created_at: knex.fn.now(),
      sms_quota: 0,
      phone_call_quota: 0,
      email_quota: 0,
      whatsapp_quota: 0,
      published: 1,
      active: 1,
      created_by: 1,
      slug: 'project_management_tool',
    },
    {
      product_id: 'prod_L2VH97kpKFcmKV',
      title: 'Plan 500 All Bundle',
      created_at: knex.fn.now(),
      sms_quota: 0,
      phone_call_quota: 0,
      email_quota: 500,
      whatsapp_quota: 500,
      published: 1,
      active: 1,
      created_by: 1,
      slug: 'plan_500_all_bundle',
    },
    {
      product_id: 'prod_L2VI51VS1ozkx2',
      title: 'Plan 1000 All Bundle',
      created_at: knex.fn.now(),
      sms_quota: 0,
      phone_call_quota: 0,
      email_quota: 1000,
      whatsapp_quota: 1000,
      published: 1,
      active: 1,
      created_by: 1,
      slug: 'plan_1000_all_bundle',
    },
    {
      product_id: 'prod_L2VOn5QjcHywiZ',
      title: 'Plan 2000 All Bundle',
      created_at: knex.fn.now(),
      sms_quota: 0,
      phone_call_quota: 0,
      email_quota: 2000,
      whatsapp_quota: 2000,
      published: 1,
      active: 1,
      created_by: 1,
      slug: 'plan_2000_all_bundle',
    },
  ]);
}
