import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries

  // Inserts seed entries
  await knex('package_prices').insert([
    {
      package_id: 11,
      stripe_price_id: 'price_1KduaKIElsOvFh8Gx37RoWqB',
      name: 'Monthly',
      price: 36,
      interval: 'month',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 11,
      stripe_price_id: 'price_1Kdub2IElsOvFh8G2Jbd62CR',
      name: 'Yearly',
      price: 360,
      interval: 'year',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 12,
      stripe_price_id: 'price_1Kduc4IElsOvFh8GeeJuZp81',
      name: 'Monthly',
      price: 69,
      interval: 'month',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 12,
      stripe_price_id: 'price_1KducJIElsOvFh8GGxUIxKdS',
      name: 'Yearly',
      price: 684,
      interval: 'year',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 13,
      stripe_price_id: 'price_1KducvIElsOvFh8GTCCuvTrw',
      name: 'Monthly',
      price: 103,
      interval: 'month',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 13,
      stripe_price_id: 'price_1KdudDIElsOvFh8Gm9LZxUuH',
      name: 'Yearly',
      price: 1080,
      interval: 'year',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 14,
      stripe_price_id: 'price_1KdudxIElsOvFh8Ga2ePNQYp',
      name: 'Monthly',
      price: 1.5,
      interval: 'month',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 14,
      stripe_price_id: 'price_1KduiwIElsOvFh8G0r3QgbA2',
      name: 'Yearly',
      price: 15,
      interval: 'year',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 15,
      stripe_price_id: 'price_1KeGDGIElsOvFh8GdxK76GE1',
      name: 'Monthly',
      price: 3,
      interval: 'month',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 15,
      stripe_price_id: 'price_1KeGDUIElsOvFh8GaeP859Mc',
      name: 'Yearly',
      price: 30,
      interval: 'year',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 19,
      stripe_price_id: 'price_1KeGLlIElsOvFh8GX7vUo6dv',
      name: 'Monthly',
      price: 33,
      interval: 'month',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 19,
      stripe_price_id: 'price_1KeGLxIElsOvFh8G00HfJEVg',
      name: 'Yearly',
      price: 338,
      interval: 'year',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 20,
      stripe_price_id: 'price_1KeHhhIElsOvFh8Gq6FT8o6v',
      name: 'Monthly',
      price: 64,
      interval: 'month',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 20,
      stripe_price_id: 'price_1KeHhxIElsOvFh8GTnxixiKs',
      name: 'Yearly',
      price: 660.0,
      interval: 'year',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 21,
      stripe_price_id: 'price_1KeHibIElsOvFh8G7eu1skCD',
      name: 'Monthly',
      price: 96,
      interval: 'month',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 21,
      stripe_price_id: 'price_1KeHiqIElsOvFh8Ggg25BSFn',
      name: 'Yearly',
      price: 1059,
      interval: 'year',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 22,
      stripe_price_id: 'price_1KeGJhIElsOvFh8GJwSAMBqX',
      name: 'Monthly',
      price: 1,
      interval: 'month',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 22,
      stripe_price_id: 'price_1KeGJwIElsOvFh8GbytTQgaj',
      name: 'Yearly',
      price: 15,
      interval: 'year',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 23,
      stripe_price_id: 'price_1KeGKSIElsOvFh8GDF6QTU08',
      name: 'Monthly',
      price: 2.5,
      interval: 'month',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 23,
      stripe_price_id: 'price_1KeGKdIElsOvFh8G7L2CeuqJ',
      name: 'Yearly',
      price: 30,
      interval: 'year',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
  ]);
}
