import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries

  // Inserts seed entries
  await knex('package_prices').insert([
    {
      package_id: 25,
      stripe_price_id: 'price_1KeI8bIElsOvFh8G49IcjXCi',
      name: 'Monthly',
      price: 36,
      interval: 'month',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 25,
      stripe_price_id: 'price_1KeI8pIElsOvFh8G0HO4sa46',
      name: 'Yearly',
      price: 360,
      interval: 'year',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 26,
      stripe_price_id: 'price_1KeIAeIElsOvFh8Ge9cIPPda',
      name: 'Monthly',
      price: 69,
      interval: 'month',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 26,
      stripe_price_id: 'price_1KeIAvIElsOvFh8GVwybtoBf',
      name: 'Yearly',
      price: 684,
      interval: 'year',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 27,
      stripe_price_id: 'price_1KeICcIElsOvFh8GNb6kxzXT',
      name: 'Monthly',
      price: 103,
      interval: 'month',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 27,
      stripe_price_id: 'price_1KeICrIElsOvFh8Gt2VZmAux',
      name: 'Yearly',
      price: 1080,
      interval: 'year',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 28,
      stripe_price_id: 'price_1KeIF8IElsOvFh8Gk7GBMErI',
      name: 'Monthly',
      price: 1.5,
      interval: 'month',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 28,
      stripe_price_id: 'price_1KeIFMIElsOvFh8GGireiNBw',
      name: 'Yearly',
      price: 15,
      interval: 'year',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 29,
      stripe_price_id: 'price_1KeIGsIElsOvFh8GXQLuqBKM',
      name: 'Monthly',
      price: 3,
      interval: 'month',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 29,
      stripe_price_id: 'price_1KeIH4IElsOvFh8G8Xa5qD5l',
      name: 'Yearly',
      price: 30,
      interval: 'year',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 33,
      stripe_price_id: 'price_1KeIMKIElsOvFh8GmYWtPbxp',
      name: 'Monthly',
      price: 33,
      interval: 'month',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 33,
      stripe_price_id: 'price_1KeIMZIElsOvFh8G6e0VF6v6',
      name: 'Yearly',
      price: 338,
      interval: 'year',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 34,
      stripe_price_id: 'price_1KeIOWIElsOvFh8Gf0surge8',
      name: 'Monthly',
      price: 64,
      interval: 'month',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 34,
      stripe_price_id: 'price_1KeIOjIElsOvFh8GXH2uEjLo',
      name: 'Yearly',
      price: 660.0,
      interval: 'year',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 35,
      stripe_price_id: 'price_1KeIQUIElsOvFh8GXsANdecC',
      name: 'Monthly',
      price: 96,
      interval: 'month',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 35,
      stripe_price_id: 'price_1KeIQhIElsOvFh8G1CrnjBXz',
      name: 'Yearly',
      price: 1059,
      interval: 'year',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 36,
      stripe_price_id: 'price_1KeIIcIElsOvFh8GzHtAcI4Z',
      name: 'Monthly',
      price: 1,
      interval: 'month',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 36,
      stripe_price_id: 'price_1KeIInIElsOvFh8GfDvwrvOk',
      name: 'Yearly',
      price: 15,
      interval: 'year',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 37,
      stripe_price_id: 'price_1KeIKPIElsOvFh8GXhURXwib',
      name: 'Monthly',
      price: 2.5,
      interval: 'month',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
    {
      package_id: 37,
      stripe_price_id: 'price_1KeIKeIElsOvFh8GU6ltJmaU',
      name: 'Yearly',
      price: 30,
      interval: 'year',
      interval_count: 1,
      active: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      currency: 'USD',
    },
  ]);
}
